### ISSUE TITLE
Any idea why Lity would cause these elements to "jump"?

### ISSUE THREAD

**Issue by cheestudio** [jsor/lity#57] opened 2016-08-22 20:22 UTC
Hey there! 

I adore Lity and use it all the time as my go-to modal (especially over the bloated Fancybox). Normally it's flawless, but I did notice a use case recently that I can't figure out. View this page here:

http://redesign.schipperweb.com/index.php/talent/

Notice when you click certain images, you see a brief flash of the other images breaking and jumping around. I tested in Chrome and FireFox. To make it more confusing, it's not consistent at all. Sometimes it will do it on one for the first click,, but not subsequent clicks. A bit maddening!

Naturally,  I don't want you to debug my code, but I'm curious what you think might be causing this? I've tried a number of things via CSS but can't seem to stop this behavior. I figured since you understand how intimately how Lity initializes, you might have a couple ideas that could get me on the right track!  :)

**Comment by cheestudio** [comment] 2016-08-22 20:41
Well, naturally, right after I figured it out right after I posted this. I am using Bourbon Neat to generate the grid of images you see there, which use floats. I migrated this to display:inline-block (along with some negative margins) and it seems to be working great.

Any ideas why floats would cause the aforementioned behavior?

**Comment by jsor** [comment] 2016-08-23 18:52
When Lity opens inline html in a lightbox, it moves the DOM node inside the lightbox and creates a placeholder node at that position in the DOM where it moves the content back when closing the lightbox (you can observe this behavior in the developer console).

I guess thats the cause for this behavior.

**Comment by cheestudio** [comment] 2016-08-23 20:13
Gotcha. And I guess there's something about floats that bug out about this. I did notice Chrome was the most susceptible to this. Using inline-block seemed to fully resolve it. I guess I could try Flexbox if all else fails...thanks for the reply! Really love the plugin and I tell everyone about it!

**Closed** 2016-08-24 07:02 UTC
