### ISSUE TITLE
Google Maps API

### ISSUE THREAD

**Issue by steamsynthetic** [jsor/lity#111] opened 2017-05-05 19:01 UTC
I have a google maps API that shows multiple locations. The map works without error if embedded directly into the page. However, inside of lity, the map does not appear. It is blank. The map is there, but I think lity may be overwriting the style of the map causing it to disappear.

**Comment by jsor** [comment] 2017-05-08 05:58
Could you setup a reproducibel test case? I suspect, some query parameters a just not transferred correctly to the embed url.

**Comment by jsor** [comment] 2017-07-10 06:08
Closing due to lack of feedback. Feel free to reopen if needed.

**Closed by jsor** 2017-07-10 06:08 UTC
