### ISSUE TITLE
open lity automaticly

### ISSUE THREAD

**Issue by ayulayol** [jsor/lity#137] opened 2017-08-29 17:37 UTC
i have created page http://ayulayol.html-5.me/sponsor/lityexample.html
how do i create an auto popup without clicking the link ? let say i want to auto popup Google Maps link?

how should i get the full code thanks

**Comment by jsor** [comment] 2017-09-08 20:00
Duplicate of #135

**Closed** 2017-09-08 20:00 UTC
